# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab08f1d412e16dc1f3c901b3ac9d87e2"
name = "hamza"
handle = "hamza-13"
application_url = "https://donate-designing-financial-commissions.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://donate-designing-financial-commissions.trycloudflare.com/auth/callback", "https://donate-designing-financial-commissions.trycloudflare.com/auth/shopify/callback", "https://donate-designing-financial-commissions.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
